services: 
  web-server:
    container_name: php-likod-serbisyo
    image: php:7.2-apache
    volumes: 
      - .:/var/www/html/:z
    ports:
      - 8000:80
  adminer:
    container_name: adminer-UI
    image: adminer:latest
    restart: always
    ports:
      - 8080:8080

  db:
    container_name: mysql-server
    image: mysql:latest
    restart: always
    environment: 
      MYSQL_ROOT_PASSWORD: 123
    volumes:
      - ./mysql:/docker-entrypoint-initdb.d:z
      - ./mysql/datadir:/var/lib/mysql:z
  phpmyadmin:
    container_name: phpmyadmin-container
    image: phpmyadmin:latest
    restart: always
    ports:
      - 8070:80
    environment:
      - PMA_ARBITRARY=1
